### ISSUE TITLE
Toubleshoot DAM data loss bug and support frontend devs

### ISSUE THREAD

**Issue by ericdrosas87** [lsst-epo/canto-dam-assets#2]
Asset data appears to be dropped when upgrading the DAM plugin from `v4.0.9` to `v4.0.12`. This may be an issue of having the migration applied, and then checking out a branch with the `v4.0.9` - possibly. Currently investigating.

**Comment by ericdrosas87** [comment]
Just confirmed that starting with a database at `v4.0.12` with DAM asset data in the DB, and then starting up Craft with `v4.0.9` after project configs are applied - the data is indeed dropped, but at this point looks like a broken image URL with the field "populated".

**Comment by ericdrosas87** [comment]
Then starting up Craft with `v4.0.12` of the plugin again and the field is no longer "populated" at all and the field appears empty.

**Comment by ericdrosas87** [comment]
Just cloned the `master` branch of `rubin-obs-api` with a `prod` DB dump, which has `v4.0.9` of the plugin with 280 DAM assets added. Confirmed I could see the assets in the Craft control panel then upgraded the DAM plugin to `v4.0.12` and I can _still_ see the assets in the Craft control panel with the same 280 DAM assets in the DB.

**Comment by khalwat** [comment]
Copy pasta from Slack:

Basically, the idea is that Project Config is config as code, and just like code, it should be pushed up to the project via Git… and the database should always be pulled down. It’s probably best that everyone on the team is kept in sync with both Project Config changes, and with the database.

A simple procedural-based workflow I’ve used is at the end of the day I make sure to push up any changes, and the next day when I start work, I pull down any changes, as well as the database.

It’s great that you’ve confirmed that there’s no data loss when going from 4.0.9  to 4.0.12 which means the migration is working correctly. I can investigate how/why the out of sync versions of the plugin and Project Config / database could cause the data loss if you like.

Thinking off of the top of my head, I can’t say for sure why that would happen, because the content is stored in the db… and I wouldn’t think anything in Project Config would affect the db in terms of the column types, but maybe Craft stores the content column types in Project Config as well for the field, I’m just not sure off hand

**Comment by ericdrosas87** [comment]
> Just confirmed that starting with a database at v4.0.12 with DAM asset data in the DB, and then starting up Craft with v4.0.9 after project configs are applied - the data is indeed dropped, but at this point looks like a broken image URL with the field "populated".

I was mistaken here - there appears to be no data loss when even reverting from version `4.0.12` to `4.0.9` of the plugin. My data loss was related to having a new DAM gallery field added to an entry which was populated with data with `4.0.12` installed, and when I reverted the plugin to `4.0.9` the project configs were applied which did not contain my new gallery field and so there was data loss.

**Comment by ericdrosas87** [comment]
Copied from Slack:

I still want to do some troubleshooting at some point, but this is what I’ve found:

It looks like that the function stack trace is:

- `services\Fields::_backupFieldColumn()` (creates the temp table)
- `services\Fields::updateColumn()`
- `services\Fields::applyFieldSave()`
- `services\Fields::handleChangedField()`

That handleChangedField() function is called as part of the project config apply process, and I’m thinking may be specific to a developer workflow where multiple developers are working on different states of the same Craft instance. I still have some sleuthing to do.

My suspicion is the following happened though:

1. The temp table is created to backup the data in a field that will have its column type changed (in services\Fields::_backupFieldColumn() )
2. The data is migrated from the content table into this temp table (in services\Fields::_backupFieldColumn() )
3. The old column is dropped in the content table (in services\Fields::_backupFieldColumn() )
4. Some error occurs and the DB transaction is “rolled back”, but this only puts the column back into the content table and doesn’t migrate the data back (a Craft or Yii-ism rolls back the transaction)

That “some error occurs” appears to be related to a project config error I’m seeing in the cloud logs: error: Trying to access array offset on value of type null

I’ve seen that project config error before, and I think it’s related to either when my DB is wildly out of date and the project config is applied, or when a bad git merge occurs and the project configs get mangled. 

It’s somewhat relieving to know that this may be a one-off issue and not indicative of some broader issue with either the DAM plugin, some other third party plugin (I suspected Neo for bit), or a Craft bug - since that means we shouldn’t encounter this specific error again in the near future, but it’s certainly possible.

I’ve already chatted with Blake a bit about some improvements to how local databases are provisioned, and I think it may help prevent issues like this moving forward.

**Comment by khalwat** [comment]
What is your updating sequence? Do you run migrations first, or apply project config changes first?

If you're not already, probably the easiest thing to do is use:

```
php craft up
```

which will run them in the proper order, behind a mutex lock.

https://craftcms.com/docs/4.x/console-commands.html#up
